#!/bin/bash
# Scans each artwork group folder, makes small thumbnails for fast loading,
# and writes images/artwork/manifest.js grouping them for the gallery.
#
# Groups map to the subsection grids in index.html:
#   cartoons  -> images/artwork/cartoons/   -> #cartoonsGrid
#   paintings -> images/artwork/paintings/  -> #paintingsGrid
# To add another group (e.g. "sketches"), add it to ARTGROUPS below, make the
# folder, and add a matching <div class="gallery__grid" id="sketchesGrid"> in index.html.
#
# Usage:  bash build-artwork.sh      (run from the site folder)
cd "$(dirname "$0")" || exit 1
BASE="images/artwork"
OUT="$BASE/manifest.js"
MAX=600
ARTGROUPS="cartoons paintings"

have_sips=0
command -v sips >/dev/null 2>&1 && have_sips=1
if [ "$have_sips" -eq 0 ]; then
  echo "note: 'sips' not found - skipping thumbnails (gallery will use full images)."
fi

printf '%s\n' '/* Auto-generated by build-artwork.sh - do not edit by hand. */' 'window.ARTWORK = {' > "$OUT"

total=0
for group in $ARTGROUPS; do
  dir="$BASE/$group"
  thumbs="$dir/thumbs"
  mkdir -p "$thumbs"
  printf '  "%s": [\n' "$group" >> "$OUT"
  count=0
  for f in "$dir"/*; do
    [ -f "$f" ] || continue
    name="${f##*/}"
    case "${name##*.}" in
      png|PNG|jpg|JPG|jpeg|JPEG|gif|GIF|webp|WEBP)
        if [ "$have_sips" -eq 1 ]; then
          if [ ! -f "$thumbs/$name" ] || [ "$f" -nt "$thumbs/$name" ]; then
            sips -Z "$MAX" "$f" --out "$thumbs/$name" >/dev/null 2>&1
          fi
        fi
        printf '    "%s",\n' "$name" >> "$OUT"
        count=$((count+1))
        ;;
    esac
  done
  printf '  ],\n' >> "$OUT"
  echo "  $group: $count image(s)"
  total=$((total+count))
done

printf '%s\n' '};' >> "$OUT"
echo "Wrote $OUT ($total image(s) total). Refresh the page."
