#!/bin/bash
# Scans each artwork group folder, makes WebP derivatives for fast loading,
# and writes images/artwork/manifest.js grouping them for the gallery.
#
# Your original files are never modified — they stay as the masters. Each one
# gets two generated WebP copies, and the site only ever serves those:
#   <group>/thumbs/<name>.webp   600px  - the gallery grid
#   <group>/web/<name>.webp     1600px  - the full-size lightbox view
#
# Groups map to the subsection grids in index.html:
#   cartoons  -> images/artwork/cartoons/   -> #cartoonsGrid
#   paintings -> images/artwork/paintings/  -> #paintingsGrid
# To add another group (e.g. "sketches"), add it to ARTGROUPS below, make the
# folder, and add a matching <div class="gallery__grid" id="sketchesGrid"> in index.html.
#
# Usage:  bash build-artwork.sh      (run from the site folder)
cd "$(dirname "$0")" || exit 1
BASE="images/artwork"
OUT="$BASE/manifest.js"
THUMB_MAX=600
FULL_MAX=1600
THUMB_QUALITY=76   # grid cells render ~230-380px, so this is imperceptible there
FULL_QUALITY=82    # lightbox is viewed close-up, so keep more detail
ARTGROUPS="cartoons paintings"

have_cwebp=0
command -v cwebp >/dev/null 2>&1 && have_cwebp=1
if [ "$have_cwebp" -eq 0 ]; then
  echo "note: 'cwebp' not found - skipping image conversion (gallery falls back to originals)."
  echo "      install it with:  brew install webp"
fi

# Shrink to at most $3 px on the long edge. cwebp's -resize needs one axis to be
# 0 to keep the aspect ratio, so pick the axis by whichever side is longer.
# The -resize args are passed as separate words rather than one string variable,
# because zsh does not word-split unquoted variables the way bash does.
make_webp() {
  src="$1"; dest="$2"; max="$3"; q="$4"
  w=$(sips -g pixelWidth "$src" 2>/dev/null | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$src" 2>/dev/null | awk '/pixelHeight/{print $2}')
  [ -n "$w" ] && [ -n "$h" ] || { cwebp -quiet -q "$q" "$src" -o "$dest" >/dev/null 2>&1; return; }
  if [ "$w" -ge "$h" ]; then
    if [ "$w" -gt "$max" ]; then
      cwebp -quiet -q "$q" -resize "$max" 0 "$src" -o "$dest" >/dev/null 2>&1; return
    fi
  elif [ "$h" -gt "$max" ]; then
    cwebp -quiet -q "$q" -resize 0 "$max" "$src" -o "$dest" >/dev/null 2>&1; return
  fi
  cwebp -quiet -q "$q" "$src" -o "$dest" >/dev/null 2>&1   # already small enough
}

printf '%s\n' '/* Auto-generated by build-artwork.sh - do not edit by hand. */' 'window.ARTWORK = {' > "$OUT"

total=0
for group in $ARTGROUPS; do
  dir="$BASE/$group"
  thumbs="$dir/thumbs"
  web="$dir/web"
  mkdir -p "$thumbs" "$web"
  printf '  "%s": [\n' "$group" >> "$OUT"
  count=0
  for f in "$dir"/*; do
    [ -f "$f" ] || continue
    name="${f##*/}"
    case "${name##*.}" in
      png|PNG|jpg|JPG|jpeg|JPEG|gif|GIF|webp|WEBP)
        stem="${name%.*}"
        if [ "$have_cwebp" -eq 1 ]; then
          # only rebuild when the original is newer than the derivative
          [ -f "$thumbs/$stem.webp" ] && [ ! "$f" -nt "$thumbs/$stem.webp" ] || \
            make_webp "$f" "$thumbs/$stem.webp" "$THUMB_MAX" "$THUMB_QUALITY"
          [ -f "$web/$stem.webp" ] && [ ! "$f" -nt "$web/$stem.webp" ] || \
            make_webp "$f" "$web/$stem.webp" "$FULL_MAX" "$FULL_QUALITY"
        fi
        printf '    "%s",\n' "$name" >> "$OUT"
        count=$((count+1))
        ;;
    esac
  done
  printf '  ],\n' >> "$OUT"
  echo "  $group: $count image(s)"
  total=$((total+count))
done

printf '%s\n' '};' >> "$OUT"

# clear out derivatives whose original has been deleted
for group in $ARTGROUPS; do
  for d in "$BASE/$group/thumbs" "$BASE/$group/web"; do
    [ -d "$d" ] || continue
    for g in "$d"/*.webp; do
      [ -f "$g" ] || continue
      stem="${g##*/}"; stem="${stem%.webp}"
      ls "$BASE/$group/$stem".* >/dev/null 2>&1 || { rm -f "$g"; echo "  removed stale $g"; }
    done
  done
done

echo "Wrote $OUT ($total image(s) total). Refresh the page."
