/* =====================================================================
   Snow White & the Seven Million Followers — cast / creative-team cards
   Drives the scroll-linked RealiTea logo, then reads window.SNOWWHITE_PEOPLE
   (images/snowwhite/people.js, generated by build-snowwhite.sh) and fills each
   .people grid whose data-group matches.
   Each person is one full-width row: headshot with name + role beneath | bio.
   ===================================================================== */
(function () {
  "use strict";

  // ---- RealiTea logo: fade in at the synopsis, get creepier toward the end ----
  const logo = document.getElementById("realitea");
  const synopsis = document.getElementById("synopsis");
  if (logo && synopsis) {
    const frames = Array.from(logo.querySelectorAll("img"));
    // scroll progress at which each later variant takes over (0 = synopsis reached, 1 = page bottom)
    const cues = [0.18, 0.36, 0.54, 0.72, 0.9];
    // page geometry is measured on load/resize only, so scrolling never forces layout
    let start = 0, end = 1, stage = -1, ticking = false;
    const measure = () => {
      const vh = window.innerHeight;
      const synTop = synopsis.getBoundingClientRect().top + window.scrollY;
      start = synTop - vh * 0.4;                       // synopsis is entering the viewport
      end = document.documentElement.scrollHeight - vh; // as far down as the page goes
    };
    const update = () => {
      ticking = false;
      const p = Math.min(1, Math.max(0, (window.scrollY - start) / Math.max(1, end - start)));
      logo.classList.toggle("is-visible", window.scrollY >= start);
      const next = Math.min(frames.length - 1, cues.filter((c) => p >= c).length);
      if (next !== stage) {
        stage = next;
        frames.forEach((img, i) => img.classList.toggle("is-on", i === stage));
      }
    };
    const onScroll = () => { if (!ticking) { ticking = true; requestAnimationFrame(update); } };
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", () => { measure(); onScroll(); });
    window.addEventListener("load", () => { measure(); update(); });
    measure(); update();

    // touch screens have no hover: tapping the logo toggles the pitch instead
    const framesEl = logo.querySelector(".realitea__frames");
    if (framesEl) framesEl.addEventListener("click", () => logo.classList.toggle("is-pitch"));

    // the ad's close button: "Are you sure?" — and the only answer is No
    const nope = document.getElementById("nope");
    const close = document.getElementById("realiteaClose");
    const no = document.getElementById("nopeNo");
    if (nope && close && no) {
      close.addEventListener("click", () => { nope.hidden = false; no.focus(); });
      no.addEventListener("click", () => { nope.hidden = true; close.focus(); });
      document.addEventListener("keydown", (e) => { if (e.key === "Escape" && !nope.hidden) { nope.hidden = true; } });
    }
  }

  const groups = Array.isArray(window.SNOWWHITE_PEOPLE) ? window.SNOWWHITE_PEOPLE : [];
  const grids = document.querySelectorAll(".people[data-group]");
  if (!groups.length || !grids.length) return;

  const esc = (s) =>
    String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

  // Escape first, then turn full URLs, bare domains and @handles into links,
  // in one pass so a link's own href never gets re-matched. Trailing sentence
  // punctuation ("site.com.", "@handle,") stays outside the link.
  const link = (href, text) =>
    '<a href="' + href + '" target="_blank" rel="noopener">' + text + "</a>";
  const linkify = (text) =>
    esc(text).replace(
      /(^|[\s(|])(?:(https?:\/\/[^\s<>()|]+?)|@([A-Za-z0-9_.]+?)|((?:[A-Za-z0-9-]+\.)+(?:com|org|net|io|co)(?:\/[^\s<>()|]*?)?))([.,;!?]*)(?=[\s)|]|$)/g,
      (m, pre, url, handle, domain, punct) =>
        pre +
        (url ? link(url, url) : handle ? link("https://instagram.com/" + handle, "@" + handle) : link("https://" + domain, domain)) +
        punct
    );

  const initials = (name) =>
    name.split(/\s+/).filter(Boolean).slice(0, 2).map((w) => w[0].toUpperCase()).join("");

  const card = (p) => {
    // optional "x% y%" focal point from the bios file, for off-center photos
    const focus = /^\d{1,3}% \d{1,3}%$/.test(p.focus || "") ? ' style="object-position:' + p.focus + '"' : "";
    const photo = p.image
      ? '<img src="' + esc(p.image) + '" alt="Headshot of ' + esc(p.name) + '" loading="lazy" decoding="async"' + focus + ">"
      : '<span class="person__initials" aria-hidden="true">' + esc(initials(p.name)) + "</span>";
    const bio = (p.bio || []).filter((t) => t.trim());
    return (
      '<article class="person reveal">' +
        '<div class="person__id">' +
          '<div class="person__photo">' + photo + "</div>" +
          '<h3 class="person__name">' + esc(p.name) + "</h3>" +
          (p.role ? '<p class="person__role">' + esc(p.role) + "</p>" : "") +
        "</div>" +
        '<div class="person__bio">' + bio.map((t) => "<p>" + linkify(t) + "</p>").join("") + "</div>" +
      "</article>"
    );
  };

  grids.forEach((grid) => {
    const group = groups.find((g) => g.name.toLowerCase() === grid.dataset.group.toLowerCase());
    const people = group ? group.people : [];
    if (!people.length) {
      grid.innerHTML = '<p class="people__empty">To be announced.</p>';
      return;
    }
    grid.innerHTML = people.map(card).join("");

    // a missing derivative degrades to the initials placeholder, not a broken image
    grid.querySelectorAll(".person__photo img").forEach((img) => {
      img.addEventListener("error", () => {
        const name = img.closest(".person").querySelector(".person__name").textContent;
        img.replaceWith(Object.assign(document.createElement("span"), {
          className: "person__initials", textContent: initials(name)
        }));
      });
    });

    // cards were added after main.js set up its observer, so reveal them here
    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const cards = grid.querySelectorAll(".reveal");
    if ("IntersectionObserver" in window && !reduceMotion) {
      const io = new IntersectionObserver((entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) { e.target.classList.add("in-view"); io.unobserve(e.target); }
        });
      }, { threshold: 0.12, rootMargin: "0px 0px -8% 0px" });
      cards.forEach((el) => io.observe(el));
    } else {
      cards.forEach((el) => el.classList.add("in-view"));
    }
  });
})();
