/* Auto-generated by build-snowwhite.sh from the show's descriptions.txt - do not edit by hand. */
window.SNOWWHITE_PEOPLE = [
  {
    "name": "Cast",
    "people": [
      {
        "name": "Jenelle Catherina",
        "role": "Snow",
        "image": "images/snowwhite/people/jenelle-catherina.webp",
        "focus": "",
        "bio": [
          "Jenelle Catherina just moved here in August from Vegas and is absolutely thrilled to be here! She was last seen premiering *The Craft’d: An Unauthorized Musical Parody* in LA as Bonnie, as Mary in *Jesus Christ Superstar* at the Palace NH, as Jane Doe in *Ride the Cyclone* and occasionally Gale Weathers in the viral *Scream’d: An Unauthorized Musical Parody* with Majestic Rep, and singing with Santa Goofy at Hong Kong Disneyland. She is so excited to be a a part of bringing this project to life!",
          "@jenellecatherina"
        ]
      },
      {
        "name": "Nicky Quirindongo",
        "role": "Beau",
        "image": "images/snowwhite/people/nicky-quirindongo.webp",
        "focus": "",
        "bio": [
          "Nicky Quirindongo (Beau) is thrilled to be making his Off-Broadway debut! A native New Yorker born and raised in Morningside Heights, Nicky holds a BFA in Dramatic Arts (Acting Concentration) and an MA in Arts Management and Entrepreneurship through a dual-degree program at The New School.",
          "Recent performance credits include appearing in a concert alongside Mandy Gonzalez and the New York Pops at Carnegie Hall for a tribute honoring Lin-Manuel Miranda (via R.Evolución Latina), directing and producing a Broadway cabaret (Stories From Latine Artists) at The Green Room 42, and taking on a role in a national commercial for a major insurance carrier.",
          "Offstage, Nicky is an avid supporter of New York sports, passionately cheering on the Knicks, Mets, Rangers, and Giants. He is represented by Linda Colonna at MC Talent Consultants, LLC."
        ]
      },
      {
        "name": "Dani Koenig",
        "role": "Queen",
        "image": "images/snowwhite/people/dani-koenig.webp",
        "focus": "",
        "bio": [
          "Danielle Koenig has been lying to you. They go by Dani. And, yeah, maybe they should change their professional name to Dani, but that feels so casual. Life is full of so many choices. This one will have to happen later.",
          "Dani - Danielle’s? - acting credits include Off-Broadway, Off-Off-Broadway, Off-Off-Off-Broadway, and Off-Off-Off-Off-Broadway credits. Among those roles, they’ve played a rat king, a well-intentioned ADHD news reporter, a butch sailor, and Michael Phelps. They also voiced Lucille Ball in Starring: Desi Arnaz for iHeart Radio.",
          "Danielle - Dani’s? - writing has been developed by Second Stage, Prospect Musicals, Musical Theatre Factory, and Circle In The Square, and their songs have been heard at Joe’s Pub, 54 Below, and Lincoln Center’s Library for the Performing Arts.",
          "They hold a BA in Theatre from UCLA and an MFA in Musical Theatre Writing from NYU.",
          "DanielleKoenig.com | IG: @danielle_koenig"
        ]
      },
      {
        "name": "Cameron Moser",
        "role": "Walter",
        "image": "images/snowwhite/people/cameron-moser.webp",
        "focus": "",
        "bio": [
          "Cameron Moser is thrilled to be a part of the cast of *Snow White and the Seven Million Followers*. Having been a performer in NY for years, Cameron often can be found on stage in both new works and beloved classics. Recent performances have included *She Loves Me*, *A Midsummer Night's Dream* (Bottom), *Twelfth Night* (Sir Andrew), *Best Little Whorehouse in Texas* (Melvin P. Thorpe), *The 25th Annual Putnam County Spelling Bee* (Leaf Coneybear) and *Spamalot* (Prince Herbert). He has also appeared in performances of new musicals such as *McMusical*, *Sing With Me: A New Musical*, *M for Marriage*, and *Forget I Said Anything*. Shout out to David and his family for their continuous support!"
        ]
      },
      {
        "name": "Charlotte Polk",
        "role": "Ensemble",
        "image": "images/snowwhite/people/charlotte-polk.webp",
        "focus": "",
        "bio": [
          "Charlotte Polk (she/they) is an actor, writer, and comedian from St. Louis. She's thrilled to be making her off-Broadway debut. Most recently, they can be seen as Cam in the web series *i’m so happy for you!!!!!!*. She loves citrus and lying down and you can find her online at ischarlottepolkstillalive.com"
        ]
      },
      {
        "name": "Kelly Brosnan",
        "role": "Ensemble",
        "image": "images/snowwhite/people/kelly-brosnan.webp",
        "focus": "",
        "bio": [
          "Kelly Brosnan (she/her) is thrilled to be making her Off-Broadway debut in *Snow White & The Seven Million Followers*! Other credits include *Junie B.’s Essential Survival Guide to School* (Junie B. Jones), *Rent* (Maureen u/s), and *Dune! The Dunesical* (Beast Rabban). She would like to thank her friends and family for their love and support, and the Snow White team for bringing her onto this hilarious project! @kebrosnan"
        ]
      }
    ]
  },
  {
    "name": "Creative team",
    "people": [
      {
        "name": "Eric Kofman",
        "role": "Writer (Book, Music & Lyrics) and Lead Producer",
        "image": "images/snowwhite/people/eric-kofman.webp",
        "focus": "",
        "bio": [
          "Eric Kofman has written lyrics for rock songs, musical sketch comedy acts, rock operas and now musicals. He is especially interested in exploring the societal implications of new technologies in his work, a theme touched on in his first major musical project, *Haber* (https://habermusical.wordpress.com/), which saw a staged concert-style reading in 2019 and is still in development. He started working on *Snow White and the Seven Million Followers* in 2020 and is delighted to be working with such a stellar creative team and cast to finally bring the show to life this year. erickofman.com"
        ]
      },
      {
        "name": "Jordan Potash",
        "role": "Co-composer and Musical Director",
        "image": "images/snowwhite/people/jordan-potash.webp",
        "focus": "",
        "bio": [
          "Jordan Potash is a composer, producer, and multi-instrumentalist hailing from Massachusetts and currently based in NYC. Over the years he's contributed his signature brand of melodic and textural stylings to a wide range of works, including scoring *Dogwood Pass*, *Trauma Bond* and the mini-series *The Impostor Syndrome*.",
          "As a performer, he's played guitar, piano, and other instruments in groups spanning various genres, and has toured with acts including Darro, Jake Brewer, and Jillian Dawn. His producer credits include artists Terror by Two, Jake Erwin, and Julia Battistin. Jordan has also released music as a solo artist and as a part of the alt-rock duo 5 Day Weekend. https://www.jordanpotashmusic.com/."
        ]
      },
      {
        "name": "Em Hausmann",
        "role": "Director",
        "image": "images/snowwhite/people/em-hausmann.webp",
        "focus": "",
        "bio": [
          "Em Hausmann is a Brooklyn-based theatre maker with a focus on development for new plays and musicals, with work spanning regionally, Off-Broadway, Off-Off-Broadway, and at various found/DIY venues across NYC. Em is passionate about championing emerging writers and building community through theatre-making processes that prioritize fun and laughter in the room. Select credits (Directing/Producing) include the world premieres of *crabby* (Ars Nova), *500 Rats: A Love Story* (HERE Arts Center), *Sea Glass* (The WP Theater), *Freak of the Week* (The Brick), *Nancy* (The Brick Aux), *Girltar Center* (Target Margin), *Your Best Odd Girl Out* (Philadelphia Fringe), *EL0N MU$K, Let Grime$ Go!* (Theaterlab), *Beethoven: Live in Concert* (Fort Salem Theater), *Miss Money HoneyBee* (The Madison Theatre), *Snow Bird* (Brooklyn Art Haus), *If You’re A Man at Night… You Gotta Be a Man in the Morning* (The Tank), *The Very Last Dance of Homeless Joe* (Theater for the New City). Associate member SDC. emhausmann.com @emhouseman"
        ]
      },
      {
        "name": "Julianna Conte",
        "role": "Choreographer",
        "image": "images/snowwhite/people/julianna-conte.webp",
        "focus": "",
        "bio": [
          "Juliana (she/they) is psyched to be a part of this team and collaborate with these incredible artists! They are a graduate of Cap21/Molloy College where they earned their BFA in Musical Theater. Juliana is a Vermont native currently living in NYC, with a passion for collaborative, new works of dance and theater. Her most recent choreography was featured in *Imposter* at The Flea Theater in collaboration with The Liminal Theater Collective. She gives endless thanks to her support system. She wouldn't be here without them! @julianaconte_. https://www.julianaconte.com/"
        ]
      },
      {
        "name": "Ari Cleveland",
        "role": "Sound Design",
        "image": "images/snowwhite/people/ari-cleveland.webp",
        "focus": "",
        "bio": [
          "Ari Cleveland is a multimedia artist specializing in sound design, AV production, and direction. They are drawn to works that amplify and celebrate the off-beat and unconventional. Select credits include *Very Blue Light* (The Tank), *On Tuesdays We Fight* (Soho Playhouse), *Measure for Measure* (The Maker's Space), *strays* (Dixon Place), *¡Violencia!* (Repertorio Español), *Needle & Bone* (The Flea), *White Elephant* (Court Square Theatre), *Is Cry You Cry'n* (MCC Theater), *Wanna Cyber?* (Loading Dock Theatre) and *24 Hour Plays: Nationals '26* (Classic Stage Company). They were a 2026 Design Wing Fellow at the Great Plains Theatre Conference and co-host the theatrical review podcast, \"The Unobstructed Review.\" @ari.chillicothe"
        ]
      },
      {
        "name": "Ellie Berry",
        "role": "Stage Manager",
        "image": "images/snowwhite/people/ellie-berry.webp",
        "focus": "57% 22%",
        "bio": [
          "Ellie Berry is a recent Ithaca College graduate who is so excited to be the Stage Manager for *Snow White and the Seven Million Followers*! Recent credits include PSM of *Matilda* at Theatre Row, SM on *THE MALL THE MALL THE MALL*, Sub ASM on *Vape! The Grease Parody*, PSM on *The Very Hungry Caterpillar* show, and ASM on the Immersive *Into the Woods*. She wants to thank the amazing team for being so awesome to work with!"
        ]
      },
      {
        "name": "Seth Tyler Black",
        "role": "Projection Design",
        "image": "images/snowwhite/people/seth-tyler-black.webp",
        "focus": "",
        "bio": [
          "Seth Tyler Black is an interdisciplinary artist and designer, experimenting with projections in theatres and exhibitions since 2011. Black can also be seen working in the art department in both film and theatrical productions, along with showcasing their own work.",
          "https://www.sethtylerblackstudio.com/"
        ]
      },
      {
        "name": "Zachary Ahmad-Kahloon",
        "role": "Lighting Design",
        "image": "images/snowwhite/people/zachary-ahmad-kahloon.webp",
        "focus": "",
        "bio": [
          "Zachary Ahmad-Kahloon (Lighting Design) Off-Broadway debut! Selected credits include work with New London Barn Playhouse (*The 25th Annual Putnam County Spelling Bee*, *Winter Wonderettes*, *Young Frankenstein*), Opera House Arts (*Outside Mullingar*), The Public Theatre (*Whit's End*), Seacoast Repertory Theatre (*HAIR*, *Natasha, Pierre & The Great Comet of 1812*, *Parade*). Zachary is the Resident Scenic and Lighting Designer and faculty at Walnut Hill School for the Arts, where he teaches Design & Production. More of his work can be found at www.zaklighting.com. @zahmadkahloon."
        ]
      },
      {
        "name": "Federica Borlenghi",
        "role": "Costume Design",
        "image": "images/snowwhite/people/federica-borlenghi.webp",
        "focus": "",
        "bio": [
          "Federica is a Brooklyn-based, multi-hyphenate artist from Milan, Italy, with a primary focus on Writing and Directing. She specializes in developing original work for the stage. She is very collaborative, experimental, community, and process-driven, and focuses on art that addresses the unaddressed gravitating around womanhood, the immigrant experience, healing, and dysfunctional realities.",
          "She also actively works in the industry as a Producer, Teaching Artist, Props Designer, and Costumes Designer in indie, non-for-profit and commercial theater spaces.  She is the Founding Editor of From The Neighborhood, an online cultural magazine highlighting the untold perspectives of the New York theater work force. Co-Curated with What Will the Neighbors Say?",
          "https://www.federicaborlenghi.com/"
        ]
      }
    ]
  }
];
